import random
from urllib.parse import quote_from_bytes


# this mf is just to get shit out of main app
class QuoteHandler:
    """Handless all quote-related functionality"""

    def __init__(self) -> None:
        pass

    def get_random_quote(self):
        """Return a ruthless motivational quote that hits like a slap to the face"""
        quotes = motivational_quotes()
        return random.choice(quotes)

    def get_random_focus_tips(self):
        """Return a short and brutal roast to trigger productivity"""
        quotes = productivity_quotes()
        return random.choice(quotes)

    def get_random_header(self):
        """Return short header quote"""
        quotes = header_quotes()
        return random.choice(quotes)

    def get_random_success(self):
        """Return a success quote"""
        quotes = success_quotes()
        return random.choice(quotes)


def motivational_quotes():
    quotes = [
        "No one’s coming. Save yourself.",
        "Stop praying for it and start bleeding for it.",
        "You’re not tired. You’re uninspired.",
        "You want discipline? Do shit you hate like you love it.",
        "Your potential is insulted by your habits.",
        "You're not behind because of bad luck—you're behind because of bad choices.",
        "That voice saying 'quit' gets quieter with every brutal rep.",
        "Waiting for perfect? That’s code for ‘never’.",
        "You talk big. Now move big.",
        "Motivation is for amateurs. Discipline builds monsters.",
        "Suffer now or suffer later—your choice has a deadline.",
        "Fear is a liar. But your results tell the truth.",
        "The man you want to be is ashamed of who you are now.",
        "Growth hurts. So does staying weak.",
        "Nobody successful got there by feeling ‘ready’.",
        "Your comfort zone is a padded cell for potential.",
        "You’re not ‘working on it’—you’re avoiding it.",
        "Quit dreaming about ‘someday’. Start bleeding today.",
        "Talk less. Execute more.",
        "You're only as strong as your weakest excuse.",
        "Tired? You haven’t even earned that feeling.",
        "Get obsessed or get beaten.",
        "Make discomfort your second home.",
        "If you're still waiting, you're already losing.",
        "Success is rented, and rent is due *every damn day*.",
        "Crush it or be crushed.",
        "You’re broke because you’re soft.",
        "Discipline is your only father.",
        "Outlift your self-doubt.",
        "Grind until pain is background noise.",
        "Nobody respects a maybe.",
        "You're not stuck—you’re lazy.",
        "Feelings are for losers.",
        "Dreams without suffering are lies.",
        "You don’t need support. You need spine.",
        "Soft life, soft legacy.",
        "Kill excuses or they’ll kill you.",
        "You’re tired because you coast.",
        "Comfort is the drug of cowards.",
        "Be your own damn savior.",
        "You weren’t born weak—you settled.",
        "Sleep like a king only after you’ve earned war.",
        "Every rep is a middle finger to average.",
        "Your grind scares the soft.",
        "Don't chase balance. Chase blood.",
        "You think too much. Act.",
        "Crave war with weakness.",
        "Ambition without action is masturbation.",
        "Build rage into results.",
        "Eat pain. Spit out growth.",
        "Success hates the lazy.",
        "No one respects intentions. Only outcomes.",
        "Victimhood is a choice.",
        "You don’t get ready—you get ruthless.",
        "Every soft choice is betrayal.",
        "Die trying or rot watching.",
        "Rise early. Suffer quietly. Win loudly.",
        "Break yourself or stay broken.",
        "Your future hates your excuses.",
        "Struggle is the tuition of kings.",
        "Lead or be forgotten.",
        "Your hustle should scare people.",
        "Starve your fear. Feed your legacy.",
        "You were made to dominate, not doubt.",
        "If you’re not hated, you’re not working.",
        "Comfort is a coffin.",
        "Bury weakness under reps.",
        "Earn scars, not likes.",
        "No pain? No pride.",
        "Do it angry. Do it alone.",
        "Suffer like a wolf, not a puppy.",
        "You’re not grinding—you’re cosplaying.",
        "Your soft habits will out you.",
        "You want comfort or conquest?",
        "Nothing grows in comfort.",
        "Every minute you wait, someone’s stealing your future.",
        "Success doesn’t care how you feel.",
        "Shut up and suffer.",
        "You fear failure because you know you're lazy.",
        "Conquer now. Cry later.",
        "Outwork your bloodline.",
        "Turn pain into payback.",
        "Excuses are just confessions.",
        "The grind owes you nothing.",
        "Success doesn't hear apologies.",
        "You bleed now or you beg later.",
        "Forget balance—build dominance.",
        "The throne isn't shared.",
        "You’re not special. Prove you’re different.",
        "Suffer daily. Win eternally.",
        "Nobody’s handing you power. Take it.",
        "You were born to lead. Act like it.",
        "Bleed more. Whine less.",
        "Discipline is masculine. Comfort is weakness.",
        "You will never be feared playing it safe.",
        "Average men chase women. Legends chase purpose.",
        "If they don’t doubt you, dream bigger.",
        "No one fears the comfortable.",
        "You’re not a king until you conquer yourself.",
        "Crush the mirror version of you daily.",
        "Sacrifice pleasure. Earn power.",
        "Do it with rage. Do it with scars.",
        "Burn the blueprint. Build the empire.",
        "Soft choices create hard regrets.",
        "F*ck potential. Show power.",
        "You can rest when you're forgotten.",
        "Weakness is louder than hunger. Kill it.",
        "You either break limits or bow to them.",
        "Grind alone. Rule with force.",
        "The path to alpha is paved with pain.",
        "Don’t wait to be ready—attack anyway.",
        "Let struggle shape you into steel.",
        "You either own the day or obey it.",
        "Get mean about your goals.",
        "You're not a man if you avoid the grind.",
        "Nobody respects a maybe.",
        "Earn your roar.",
    ]
    return quotes


def productivity_quotes():
    quotes = [
        "You’ve mastered distraction. Congrats on nothing.",
        "Slack now, cry later.",
        "You call it burnout. I call it excuses in disguise.",
        "You want results? Trade dopamine for discipline.",
        "You keep dodging effort like it’s optional. It’s not.",
        "You don’t lack time. You lack priorities.",
        "Comfort is killing your future self.",
        "You’re broke because you act like you’re rich in time.",
        "Want more output? Start by shutting up and starting.",
        "You don’t need coffee. You need character.",
        "If you treated your goals like your phone, you’d be unstoppable.",
        "You’re drowning in excuses disguised as reasons.",
        "Scrolling won’t make you successful.",
        "You're not working—you’re playing adult dress-up.",
        "Deadlines don’t care about your mood swings.",
        "You lose the day in the first 10 minutes. Wake up right.",
        "Keep ghosting your goals and watch them haunt you later.",
        "You say you want success. Your actions scream 'I don't'.",
        "You’re not built different. You’re just undisciplined.",
        "Less complaining. More becoming.",
        "Procrastination is suicide on a payment plan.",
        "The task won’t finish itself. Neither will your legacy.",
        "Winners do. Losers delay.",
        "You don’t need motivation. You need momentum.",
        "Break focus, break progress.",
        "Comfort makes you forget you’re behind.",
        "You wasted today. Admit it, then fix it.",
        "That ‘later’ you keep saying? It’s killing your future.",
        "Multitasking is just doing everything badly.",
        "Discipline makes hours stretch. Distraction kills them.",
        "You don’t run out of time. You run out of will.",
        "Your phone is feeding your failure.",
        "No grind. No shine.",
        "Productivity starts with killing comfort.",
        "Postpone nothing. Execute everything.",
        "Most people are busy being useless.",
        "Your to-do list isn’t a wishlist. It's a war plan.",
        "Thinking isn’t doing. Planning isn’t progress.",
        "You’re not overwhelmed. You’re unorganized.",
        "You say you’re a beast, but you work like a breeze.",
        "High performers don’t ‘feel like it.’ They just do it.",
        "You’re not under pressure. You’re underprepared.",
        "You can’t be focused and entertained at the same time.",
        "Your effort should intimidate your laziness.",
        "If it doesn’t challenge you, it’s wasting you.",
        "Hustle until procrastination fears you.",
        "Busy is a lie. Productive is truth.",
        "You waste hours and wonder why life’s hard.",
        "Put down the phone. Pick up your mission.",
        "Time doesn’t care how you feel.",
        "Want momentum? Get moving.",
        "Start fast. Finish ruthless.",
        "You don't need more time. You need less bullshit.",
        "Execution > Ideas.",
        "Nobody who scrolls for 3 hours wins the day.",
        "Discipline makes minutes matter.",
        "Today’s habits are tomorrow’s trophies or tombstones.",
        "Your excuses are stealing your empire.",
        "Shiny objects are for weak minds.",
        "You’ve got 24 hours. What’s your excuse?",
        "Build systems, not just dreams.",
        "Success hates slackers.",
        "Clear desk. Clear mission.",
        "One more scroll, one less goal.",
        "You can’t Netflix your way to greatness.",
        "You keep planning. Winners keep doing.",
        "That thing you’re avoiding? It’s the one that matters.",
        "Every task skipped is a step backward.",
        "Your comfort is your competitor’s opportunity.",
        "Do the work. Then double it.",
        "Sleep like a king only when you’ve worked like a killer.",
        "You either own your time, or time owns you.",
        "Focus is rare. Master it. Weaponize it.",
        "You delay because deep down, you're scared of effort.",
        "Don’t be busy—be brutal.",
        "Time isn’t the problem. Weak priorities are.",
        "Every excuse is you betraying future you.",
        "Stop optimizing. Start attacking.",
        "Get obsessed with output.",
        "If it doesn’t build your future, cut it.",
        "Success is productivity, not potential.",
        "Your energy is spent—now prove it was invested.",
        "The clock doesn’t stop because you're tired.",
        "If your calendar is empty, so is your ambition.",
        "No one’s going to organize your life for you.",
        "You said tomorrow. That was three weeks ago.",
        "Discipline is louder than any alarm clock.",
        "Meet your goals or make excuses. Never both.",
        "You aren’t burnt out. You’re just bored of mediocrity.",
        "No distraction is harmless when you're losing time.",
        "Schedule your success or wing your failure.",
        "Hard work now or regret forever. Choose fast.",
        "Your results reflect your discipline. Period.",
        "Each wasted minute is a thief in disguise.",
        "Forget hacks. Do hard things quickly.",
        "No breaks until breakthroughs.",
        "Most people fail quietly, while looking productive.",
        "Success doesn’t want your intentions. It wants your output.",
    ]
    return quotes


def header_quotes():
    quotes = [
        "No plan? No future.",
        "Excuses feed failure.",
        "Grind louder.",
        "Get up or give up.",
        "Quit comfort. Chase chaos.",
        "Stop lying to yourself.",
        "Execution over everything.",
        "Beast mode is a decision.",
        "Dreams demand sweat.",
        "Discipline is freedom.",
        "Silence the inner bitch.",
        "Make pain pay rent.",
        "Earn your name.",
        "Softness kills greatness.",
        "Suffer now. Shine later.",
        "Results > reasons.",
        "Destroy doubt daily.",
        "Be relentless. Not reasonable.",
        "Show up. Or shut up.",
        "You’ve stalled long enough.",
        "You owe your goals a fight.",
        "Your laziness writes your legacy.",
        "Run toward the discomfort.",
        "Too tired? That’s when it starts.",
        "Move or be moved.",
        "Excuses are lies.",
        "No grind. No glory.",
        "Kill comfort.",
        "Talk less. Do more.",
        "Earn every inch.",
        "Outwork everyone.",
        "Dominate. Don’t negotiate.",
        "Starve your weakness.",
        "Power over pity.",
        "Success won't wait.",
        "Hustle or rust.",
        "Train savage. Live savage.",
        "Crush or crumble.",
        "Comfort is a coffin.",
        "Weakness is loud.",
        "Focus is a weapon.",
        "Discipline is savage love.",
        "Attack the day.",
        "Fail forward. Fast.",
        "Make chaos obey.",
        "Obsessed wins.",
        "Break limits daily.",
        "Be the storm.",
        "Lions don’t pause.",
        "Outlast your excuses.",
        "Own the outcome.",
        "Earn. Don’t expect.",
        "Your move. Right now.",
        "No mercy. Just action.",
        "Pain is payment.",
        "Quit later. Do now.",
        "Dead weight gets dropped.",
        "Live harder.",
        "Show scars, not softness.",
        "Comfort kills kings.",
        "Keep crushing.",
        "Fear dies in effort.",
        "Push past pity.",
        "Rise. Wreck. Repeat.",
        "Get fierce. Stay sharp.",
        "Strike first. Strike hard.",
        "Work is worship.",
        "Bleed forward.",
        "Rest is a reward, not a right.",
        "War mode. Always.",
        "Execute like it’s owed.",
        "Get brutal. Stay focused.",
        "No soft steps.",
        "Mediocrity is a choice.",
        "Hunger never lies.",
        "Burn the excuses.",
        "Stay cold. Move hard.",
        "All in. All day.",
        "Rise on routine.",
        "No fallback. Just fight.",
        "Daily destruction of doubt.",
        "Hard choices, hard results.",
        "Eat the struggle.",
        "Make time. Don’t wait.",
        "Choke out weakness.",
        "Stay sharp. Strike hard.",
        "Winners don’t wait.",
        "Refuse rest. Earn results.",
        "Bury your old self.",
        "Power is earned daily.",
        "Outrageous effort only.",
        "Warrior hours only.",
        "No space for softness.",
        "Mind right. Grind right.",
        "No drift. Just drive.",
        "Do it anyway.",
        "No signal. Still savage.",
        "You rest, you rust.",
        "Blood fuels progress.",
        "Doubt dies in discipline.",
        "All pressure. No pause.",
        "Earn oxygen.",
        "Stop stopping.",
        "Harden up.",
        "Kill the quit.",
        "Only action ages well.",
        "Outwork the timeline.",
        "Quitters don’t question. They disappear.",
        "Ignore the noise. Build the weapon.",
        "Work like legacy’s watching.",
        "Today owes you nothing.",
        "Stay dangerous.",
        "Break rules. Break records.",
        "Don’t chill. Charge.",
        "Fight through the fog.",
        "Done is the only flex.",
        "Crush comfort zones.",
        "You’re on the clock.",
        "Discipline defines you.",
        "Earn the silence.",
        "This is your warning shot.",
    ]
    return quotes


def success_quotes():
    quotes = [
        "Good. But you’re not done yet.",
        "Win logged. Now keep stacking.",
        "Grind complete. No let-up tomorrow.",
        "You did something. Now do more.",
        "Success is quiet. Stay louder with actions.",
        "Clocked in. Clocked out. Repeat until elite.",
        "One win doesn’t make a warrior.",
        "Progress noted. Complacency denied.",
        "You showed up. That’s the baseline.",
        "Earned. Not gifted.",
        "Stack that rep. Forget the rest.",
        "Done today? Good. Now dominate tomorrow.",
        "You don’t celebrate progress. You outgrow it.",
        "Results delivered. Standards rising.",
        "You fought for this. Now fight again.",
        "Momentum is a muscle. Flex it daily.",
        "One brick laid. The wall’s not done.",
        "Success is forged in silence.",
        "No trophies for excuses.",
        "Win ugly. Win anyway.",
        "Don’t rest on the first.",
        "Success demands savage consistency.",
        "Earn it. Every damn day.",
        "Victory favors the relentless.",
        "No pause. Just progress.",
        "The grind never quits.",
        "Fall seven times. Rise eight.",
        "Done is better than perfect.",
        "Your hustle defines your horizon.",
        "No luck. Just grind.",
        "Master the process or be mastered.",
        "Sweat writes your legacy.",
        "Success is the sum of small wins.",
        "Own your failures. Then own your wins.",
        "Be the storm your goals fear.",
        "Champions bleed discipline.",
        "Success whispers. Hustle screams.",
        "No days off from domination.",
        "Push limits, then push harder.",
        "Elite status is earned, not wished.",
        "Every rep is a battle won.",
        "Fearless in pursuit, relentless in action.",
        "Victory demands more than desire.",
        "Success waits for no one.",
        "Turn pain into power.",
        "The grind separates the great.",
        "Legacy is built on discipline.",
        "Small wins compound to greatness.",
        "Earn respect. Never demand it.",
        "Your work ethic defines your future.",
        "Sweat now. Shine forever.",
        "Discipline beats talent every time.",
        "Stay obsessed or stay average.",
        "Results are earned, not given.",
        "No excuses. No mercy.",
        "The grind is your true currency.",
        "Push harder. Get stronger.",
        "Own the day or be owned by it.",
        "Success is a brutal grind.",
        "Make your hustle undeniable.",
        "Hard work silences doubters.",
        "Victory loves preparation.",
        "Run your race. Win your war.",
        "Consistency kills competition.",
        "Outwork yesterday.",
        "Hustle beats hope.",
        "Commit fully or stay stuck.",
        "No quitters ever win.",
    ]
    return quotes
